# Generated by Django 6.0.2 on 2026-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['published'], name='blog_post_publish_8fcab7_idx'),
        ),
    ]
