# Generated by Django 6.0.2 on 2026-02-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
